### ISSUE TITLE
Run tests with Github Actions

### ISSUE THREAD

**Issue by felipeaugusto1** [wix/Detox#2985]
I wasn't able to find an answer for this so I'd like to ask here. Is it possible to run the tests without open the emulator? If so, how? If not, do you guys have any code snippet explaining how to set up an android emulator and running the tests with Github Actions?

**Comment by tsirlucas** [comment]
researching it right now and found this issue, these are the most interesting repos i've found:

https://github.com/reime005/react-native-spaceviewer/blob/master/.github/workflows/android.yml

https://github.com/invertase/react-native-firebase/tree/master/.github/workflows

**Comment by felipeaugusto1** [comment]
My issue is that I'm trying to use Java 11, so when I install it I'm not able to install the Android emulator. If I use Java 8 I'm able to install the emulator however my detox build doesn't work due to a library incompatibility.

**Comment by tsirlucas** [comment]
Yeah I didnt have the chance to give it a try to java 11 yet. Im still using java 8 and its working fine for my case

**Comment by d4vidi** [comment]
@felipeaugusto1 Detox allows for the implementation of custom drivers - which, if sophisticated enough, could allow for the mocking of even a whole emulator / simulator. However, one must ask: what is the motivation for doing so?

As for Android stability on CI -- I'm finalizing a blogpost on this very painful issue. TL;DR stability can be achieved. I'll post it soon on our [twitter account](https://twitter.com/detoxe2e).

**Comment by d4vidi** [comment]
Last but not least, we haven't made the necessary adjustments for Java 11. @felipeaugusto1 Could you describe what the exact issue is when upgrading from 8 to 11? (emulator wouldn't start?)

**Comment by felipeaugusto1** [comment]
@d4vidi happy to hear that.

About the java version: in a nutshell, I'm able to run all the tests locally on my laptop (with java 11). The only issue is running them on Github CI.

With java 8:
One of my app dependencies throw an error `java.lang.AssertionError: annotationType(): unrecognized Attribute name MODULE (class com.sun.tools.javac.util.UnsharedNameTable$NameImpl)`

With java 11:
I'm not able to install the android emulator. I get `Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema`. I believe this happens because I need to accept all the SDK licenses (which I haven't found a way to accept automatically by command line)

**Comment by d4vidi** [comment]
What you've described regarding Java 8 sounds highly specific. There's not much I can do about it, offhand.
As for Java 11, I leave to you to understand the connection between the error and the SDK licenses... 😄 But as for automated acceptance of liceneses, you can try:
```
yes | sdkmanager --licenses
```

**Comment by felipeaugusto1** [comment]
I've already tried `yes | sdkmanager --licenses` and I get the same error

**Comment by d4vidi** [comment]
Then maybe the error is not associated with licenses, nevertheless?
