### ISSUE TITLE
TabBarTestId is always a not found element

### ISSUE THREAD

**Issue by hajermay** [wix/detox#935]
const MoreStack = createStackNavigator({
  MoreScreen: {
    screen: MoreScreen,
    navigationOptions: {
      headerTitle: <HeaderCenter title="Search people, investments, groups..." />,
      headerStyle: styles.headerCentered,
    },
  },

MoreStack.navigationOptions = {
  tabBarIcon: ({ tintColor }) => (<Icon style={styles.iconStyleWithoutBadge} size={22} color={tintColor} name="ellipsis-h" />),
  TabBarTestId: 'Child',
};

const PrimaryNav = createBottomTabNavigator({
  HomeStack,
  NotificationsStack,
  InboxStack,
  MoreStack,
},

  it('should open second menu on tabbar', async () => {
          await element(by.id('Child')).tap(); 
         });

**Comment by juand89** [comment]
what error do you have? I had the same problem but solved using element(by.id('TabBarID')).atIndex(0)

**Comment by hajermay** [comment]
@juand89  what is the version of react-navigation you have used at that case

**Comment by juand89** [comment]
@hajermay version 2.6.2

**Comment by hajermay** [comment]
@juand89  im using a little bit old project with version 2.0.0  of react navigation i can guess the problem it comes from that reason.

**Comment by juand89** [comment]
@hajermay yes you are right! I changed the version of react navigation to 2.0.0 and the test fails

**Comment by hajermay** [comment]
But my problem when i upgrade to 2.2.5 for exemple it always show me
navigation.getChildNavigation is not a function i have just create this
issue on react-navigation
