### ISSUE TITLE
Unable to build android app on v20.20.3

### ISSUE THREAD

**Issue by cortisiko** [wix/Detox#4462]
### What happened?

I am running into an issue when updating to v20.20.3 on android. When i build the app the below error appears

> Task :app:compileFlaskDebugAndroidTestJavaWithJavac FAILED
/Users/curtis/Documents/metamask-mobile/android/app/src/androidTest/java/com/metamask/DetoxTest.java:3: error: cannot access Detox
import com.wix.detox.Detox;
                    ^
  bad class file: .gradle/caches/transforms-3/093957821fe73cc2652732086e88016c/transformed/jetified-detox-20.20.3-api.jar(/com/wix/detox/Detox.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
android/app/src/androidTest/java/com/metamask/DetoxTest.java:12: error: cannot access DetoxConfig
import com.wix.detox.config.DetoxConfig;

At this point in time it is unclear what this error means. If I were to downgrade to any version < 20.20 I can successfully build the app for testing. 

### What was the expected behaviour?

I should be able to build and run the detox on the latest version. 

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### In what environment did this happen?

Detox version: 20.20.3
React Native version: 0.71.15
Has Fabric (React Native's new rendering system) enabled: (yes/no) 
Node version: 18
Device model: 
Android version: 
Test-runner (select one): jest / other

### Detox logs

<details><summary>Detox logs</summary>

```
paste logs here!
```

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste your device.log here!
```

</details>

**Comment by BlinkVonDoom** [comment]
I was able to get around it by using 

`androidTestImplementation('com.wix:detox-legacy:+')` in `app/build.grale` instead of `androidTestImplementation('com.wix:detox:+')`

https://github.com/wix/Detox/releases/tag/20.18.5

**Comment by cortisiko** [comment]
hey @BlinkVonDoom thanks for replying! Your recommendation works!!

**Comment by JB712** [comment]
> I was able to get around it by using
> 
> `androidTestImplementation('com.wix:detox-legacy:+')` in `app/build.grale` instead of `androidTestImplementation('com.wix:detox:+')`
> 
> https://github.com/wix/Detox/releases/tag/20.18.5

I use Java v18 and it worked for me too
