### ISSUE TITLE
DetoxRuntimeError: The pending request #65 ("invoke") has been rejected | Signal 6 was raised (6   libc++abi.dylib  0x000000010c351692 abort_message + 241)

### ISSUE THREAD

**Issue by baskarkarthik** [wix/Detox#3577]
### What happened?
While trying to close the keypad using `\n`, app hangs and script fails

Scenario: Type username & password and tap login button
Issue:
In iOS, while trying to type a username keypad opens which hides the password field. After typing username while trying to close the keypad using '\n', app hangs and test fails

`await element(by.id('usrname')).typeText('usernameData');`
`await element(by.id('usrname')).typeText('\n');`

Works fine in **Detox@17.14.9**
After upgrading detox showing some issue
**Detox@19.10.0 & @19.11.0**

> RCTFatalException: Unhandled JS Exception: TypeError: n.scrollResponderScrollTo is not a function. (In 'n.scrollResponderScrollTo({x:e,y:o,animated:t})', 'n.scrollResponderScrollTo' is undefined)
> Unhandled JS Exception: TypeError: n.scrollResponderScrollTo is not a function. (In 'n.scrollResponderScrollTo({x:e,y:o,animated:t})', 'n.scrollResponderScrollTo' is undefined

**Detox@19.8.4**

>  DetoxRuntimeError: The pending request #74 ("invoke") has been rejected due to the following error:
> The app has crashed, see the details below:
> Signal 6 was raised

Workarounds which not works:
Installing `react-native-keyboard-aware-scroll-view` version 0.9.5
'Connect Hardware keyboard' in Simulator (Simulator -> i/o -> Keyboard -> Connect Hardware keyboard) 

### What was the expected behaviour?

While moving from one textfield to another, keypad should close without any issue.

### Was it tested on latest Detox?

- [X] I have tested this issue on the latest Detox release and it still reproduces.

### Did your test throw out a timeout?

- [X] I have followed the instructions under [Identifying which synchronization mechanism causes us to wait too much](https://wix.github.io/Detox/docs/troubleshooting/synchronization#identifying-which-synchronization-mechanism-causes-us-to-wait-too-much).

### Help us reproduce this issue!

Get iOS app that has a page with multiple text fields, while typing in one text field keypad should hide other(s)

use detox v19.8.4, when we try to close keypad it throws 
> RCTFatalException: Unhandled JS Exception: TypeError: n.scrollResponderScrollTo is not a function.

use detox v19.10.0 or v19.11.0, when we try to close keypad it throws 
> DetoxRuntimeError: The pending request #102 ("invoke") has been rejected due to the following error:
> The app has crashed, see the details below:
> Signal 6 was raised

### In what environment did this happen?

Detox version: v19.8.4, v19.10.0, v19.11.0
React Native version: v0.68.2
Node version: v18.7.0
Device model: Simulator - iPhone 12 pro max
iOS version: 14.5
macOS version: macOS monterey (v12.4)
Xcode version: v13.2.1
Test-runner : mocha 

### Detox logs

<details><summary>Detox logs</summary>

**v19.10.0, v19.11.0**

10:11:44.491 detox[49546] ERROR: at e2e/LoginScreenElements.js:504:15 
 The pending request #27 ("invoke") has been rejected due to the following error:

The app has crashed, see the details below:

Exception was thrown: 
RCTFatalException: Unhandled JS Exception: TypeError: n.scrollResponderScrollTo is not a function. (In 'n.scrollResponderScrollTo({x:e,y:o,animated:t})', 'n.scrollResponderScrollTo' is undefined)
Unhandled JS Exception: TypeError: n.scrollResponderScrollTo is not a function. (In 'n.scrollResponderScrollTo({x:e,y:o,animated:t})', 'n.scrollResponderScrollTo' is undefined..., stack:
<unknown>@1324:1797
<unknown>@1324:4267
value@192:1071
value@228:3579
<unknown>@228:758
value@228:2582
value@228:730
value@(null):(null)

(
	0   CoreFoundation                      0x00007fff20422faa __exceptionPreprocess + 226
	1   libobjc.A.dylib                     0x00007fff20193ff5 objc_exception_throw + 48
	2   ServiceApp                              0x0000000100a5bb1b RCTFormatError + 0
	3   ServiceApp                              0x0000000100adfe33 -[RCTExceptionsManager reportFatal:stack:exceptionId:] + 503
	4   ServiceApp                              0x0000000100ae07a3 -[RCTExceptionsManager reportException:] + 1570
	5   CoreFoundation                      0x00007fff20429a3c __invoking___ + 140
	6   CoreFoundation                      0x00007fff20426c6f -[NSInvocation invoke] + 305
	7   CoreFoundation                      0x00007fff20426f02 -[NSInvocation invokeWithTarget:] + 70
	8   ServiceApp                              0x0000000100a907c4 -[RCTModuleMethod invokeWithBridge:module:arguments:] + 595
	9   ServiceApp                              0x0000000100a930ae facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&, int, (anonymous namespace)::SchedulingContext) + 574
	10  ServiceApp                              0x0000000100a92cda invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int) + 103
	11  DetoxSync                           0x00000001029fbaa7 ____detox_sync_dispatch_wrapper_block_invoke + 23
	12  libdispatch.dylib                   0x00007fff2010670d _dispatch_call_block_and_release + 12
	13  libdispatch.dylib                   0x00007fff201078df _dispatch_client_callout + 8
	14  libdispatch.dylib                   0x00007fff2010de15 _dispatch_lane_serial_drain + 715
	15  libdispatch.dylib                   0x00007fff2010e98c _dispatch_lane_invoke + 400
	16  libdispatch.dylib                   0x00007fff20118f81 _dispatch_workloop_worker_thread + 772
	17  libsystem_pthread.dylib             0x00007fff60347fd0 _pthread_wqthread + 326
	18  libsystem_pthread.dylib             0x00007fff60346f57 start_wqthread + 15
)
    at LoginScreеn.closeKeyboard (/Users/usr/Documents/Work/MobileAutomation/Projects/Detox_Upgrade/ServiceProject/e2e/LoginElements.js:502:116)
    at Context.<anonymous> (/Users/usr/Documents/Work/MobileAutomation/Projects/Detox_Upgrade/ServiceProject/e2e/LoginTest.spec.js:43:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  name: 'DetoxRuntimeError'
}

---------------------------------------------------------------------------------------------------------------------------
**v19.8.4**
DetoxRuntimeError: The pending request #102 ("invoke") has been rejected due to the following error:

The app has crashed, see the details below:

Signal 6 was raised
(
	0   Detox                               0x000000010a29dc15 +[NSThread(DetoxUtils) dtx_demangledCallStackSymbols] + 37
	1   Detox                               0x000000010a2a0670 __DTXHandleCrash + 464
	2   Detox                               0x000000010a2a0db1 __DTXHandleSignal + 59
	3   libsystem_platform.dylib            0x00007fff6033ddfd _sigtramp + 29
	4   ???                                 0x0000000000000001 0x0 + 1
	5   libsystem_c.dylib                   0x00007fff200fbcb5 abort + 120
	6   libc++abi.dylib                     0x00007fff20254692 abort_message + 241
	7   libc++abi.dylib                     0x00007fff20245dfd demangling_unexpected_handler() + 0
	8   libobjc.A.dylib                     0x00007fff20179ace _objc_terminate() + 96
	9   ServiceApp                              0x0000000108e6be29 FIRCLSTerminateHandler() + 358
	10  Detox                               0x000000010a2a12a6 __dtx_terminate() + 157
	11  libc++abi.dylib                     0x00007fff20253aa7 std::__terminate(void (*)()) + 8
	12  libc++abi.dylib                     0x00007fff20253a49 std::terminate() + 41
	13  libdispatch.dylib                   0x00007fff201078f3 _dispatch_client_callout + 28
	14  libdispatch.dylib                   0x00007fff2010de15 _dispatch_lane_serial_drain + 715
	15  libdispatch.dylib                   0x00007fff2010e98c _dispatch_lane_invoke + 400
	16  libdispatch.dylib                   0x00007fff20118f81 _dispatch_workloop_worker_thread + 772
	17  libsystem_pthread.dylib             0x00007fff60347fd0 _pthread_wqthread + 326
	18  libsystem_pthread.dylib             0x00007fff60346f57 start_wqthread + 15
)
    at LoginScreеn.closeKeyboard (/Users/usr/Documents/Work/MobileAutomation/Projects/Detox_Upgrade/ServiceApp/e2e/LoginScreenElements.js:502:116)
    at Context.<anonymous> (/Users/usr/Documents/Work/MobileAutomation/Projects/Detox_Upgrade/ServiceApp/e2e/LoginScreenTest.spec.js:43:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

</details>

### Device logs

<details><summary>Device logs</summary>

```
paste logs here!
```

</details>

### More data, please!

<img width="893" alt="Detox_Issue" src="https://user-images.githubusercontent.com/31349340/191903926-4a1a8929-64f2-4823-b8a9-0d5a0591d32a.png">

_No response_

**Comment by baskarkarthik** [comment]
Hi @d4vidi / @wixmobile team
Any fix for my above issue, this issue completely blocking my automation. I can't proceed further.

**Comment by baskarkarthik** [comment]
Hi @asafkorem 
Any fix or update on the above issue, because of issue I've been completely blocked for a long time
