### PR TITLE
chore: upgrade @react-native-community/datetimepicker

### PR DESCRIPTION
**Pull request by noomorph**
## Description

This should fix a compilation error in `detox/test` on Xcode 15.3.
I confirmed that it works on Xcode 15.2 locally as well.

### CODE REVIEW

**Comment by asafkorem** [comment]
See: https://github.com/react-native-datetimepicker/datetimepicker/pull/868
